### ISSUE TITLE
El programador creara un esquema como guía para el equipo

### ISSUE THREAD

**Issue by guillermosequera** [patoteGo/telocambio#55]
- [x] Crear maqueta en papel y compartir pantallas en foto
- [ ] Crear el home
- [ ] Crear pagina de un producto
- [ ] Cards de cada producto

**Comment by patoteGo** [comment]
Test foto 
![image](https://user-images.githubusercontent.com/17224644/83968608-5d2dcf00-a898-11ea-9cef-870d3095c854.png)

**Comment by patoteGo** [comment]
![image](https://user-images.githubusercontent.com/17224644/83968627-7b93ca80-a898-11ea-90aa-cdcb91288d75.png)

**Comment by anitamarie** [comment]
Dibujo de maqueta:
![maqueta](https://user-images.githubusercontent.com/52432961/84091497-89456f00-a9c2-11ea-97e5-4a9afa65a07e.png)

**Comment by anitamarie** [comment]
Dibujo de maqueta:
![maqueta](https://user-images.githubusercontent.com/52432961/84091582-d75a7280-a9c2-11ea-8830-8f6cc48a48cf.png)
